name: SelfHostCheck CI

# Controls when the workflow will run
on:
  schedule:
    # Runs "at minute 0 every hour" (see https://crontab.guru)
    - cron: '0 */12 * * *'
    branches: [ "main" ]
  # manually
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  checkup:
    runs-on: ubuntu-latest
    steps:
      - name: Check http status code of production site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["${{ secrets.URLTOCHECK }}"]'
          topic: "${{ secrets.TOPICTONOTIFY }}"
          expected: '[200]'
      - name: ntfy-failed-notifications
        uses: niniyas/ntfy-action@master
        if: failure()
        with:
          url: 'https://ntfy.sh'
          topic: '$topic'
          priority: 5
          tags: +1,action,failed
          details: Site down!
