name: SelfHostCheck CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 */12 * * *'

  # manually
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  checkup:
    runs-on: ubuntu-latest
    steps:
      - name: Check http status code of production site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["${{ secrets.URLTOCHECK }}"]' #sites are comma separated
          expected: '[200]'
      - name: ntfy-failed-notifications
        uses: niniyas/ntfy-action@master
        if: failure()
        with:
          url: 'https://ntfy.sh'
          topic: "${{ secrets.TOPICTONOTIFY }}"
          priority: 5
          tags: +1,action,failed
          details: OMG Site down!
